// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wms: [{type: 'autogenerated', dirName: 'wms'}],
  ilnawa: [{type: 'autogenerated', dirName: 'ilnawa'}],
};

module.exports = sidebars;